from typing import List, Dict, TypedDict, Optional


class TableSpec(TypedDict):
    sheet_name: str
    row_tag: str
    columns: List[str]
    root_path: Optional[List[str]]


# Constants for each table's sheet name and columns. These are used by the generic export function in export.py.
# ---- CommProperties ----
COMM_PROPERTIES_SHEET_NAME = "CommProperties"
COMM_PROPERTIES_COLUMNS: List[str] = [
    "Record_ID",
    "Source_Id",
    "Source_Code",
    "Address1",
    "Address2",
    "Address3",
    "Address4",
    "City",
    "State",
    "ZipCode",
    "Residential",
    "Commercial",
    "Association",
    "Student",
    "Senior",
    "Military",
    "Affordable",
    "PublicHousing",
    "International",
    "CanadianSocialHousing",
    "AssocSubType",
    "EndOfYear",
    "Inactive",
    "InactiveDate",
    "PurchasePrice",
    "NCREIFNumber",
    "AcquisitionDate",
    "DispositionDate",
    "LateType",
    "LatePercent",
    "LatePerDay",
    "LateMin",
    "Type2",
    "IsEstate",
    "ContractExpDate",
    "ContractReserve",
    "Commision",
    "MinCommision",
]

# ---- LockOuts ----
LOCK_OUTS_SHEET_NAME = "LockOuts"
LOCK_OUTS_COLUMNS: List[str] = [
    "Record_ID",
    "Source_ID",
    "PropertyID",
    "DTMMYY0",
    "DTMMYY1",
    "DTMMYY2",
    "DTMMYY3",
    "DTMMYY4",
    "DTMMYY5",
    "ICLOSEDAY",
    "HCHART",
    "DTCHARGEPOST",
    "IFUNDTYPE",
    "PERFORMANCE",
    "dtLeaseWeek",
    "dtCurrentCAMYear",
    "dtDailyClose",
]

# ---- ResSourceNames ----
RES_SOURCE_NAMES_SHEET_NAME = "ResSourceNames"
RES_SOURCE_NAMES_COLUMNS: List[str] = [
    "Record_ID",
    "Source_ID",
    "PropertyId",
    "SourceName",
    "InactiveDate",
    "Portal",
]

# ---- ResAgentNames ----
RES_AGENT_NAMES_SHEET_NAME = "ResAgentNames"
RES_AGENT_NAMES_COLUMNS: List[str] = [
    "Record_ID",
    "Source_ID",
    "Source_Code",
    "PropertyId",
    "AgentName",
    "DateEnd",
    "EmployeeID",
    "StartDate",
]

# ---- ResCancelReasons ----
RES_CANCEL_REASONS_SHEET_NAME = "ResCancelReasons"
RES_CANCEL_REASONS_COLUMNS: List[str] = [
    "Record_ID",
    "Source_ID",
    "PropertyId",
    "Reason",
    "InactiveDate",
    "ContactResult",
    "UnqualifiedTraffic",
    "CancelApplication",
    "Deny",
    "CancelMoveIn",
    "ApproveApplication",
]

# ---- ResRentableItemsTypes ----
RES_RENTABLE_ITEMS_TYPES_SHEET_NAME = "ResRentableItemsTypes"
RES_RENTABLE_ITEMS_TYPES_COLUMNS: List[str] = [
    "Record_ID",
    "Source_ID",
    "Source_Code",
    "PropertyId",
    "ChargeCodeId",
    "Description",
    "Rent",
    "Deposit",
    "Tax",
    "ServiceCharge",
]

# ---- CommonPropOptions ----
COMMON_PROP_OPTIONS_SHEET_NAME = "CommonPropOptions"
COMMON_PROP_OPTIONS_COLUMNS: List[str] = [
    "Record_ID",
    "PropertyID",
    "ObjectName",
    "Type",
    "StringValue",
    "HandleValue",
    "DtDate",
]

# --- ResPropertyAmenities ----
RES_PROPERTY_AMENITIES_SHEET_NAME = "ResPropertyAmenities"
RES_PROPERTY_AMENITIES_COLUMNS: List[str] = [
    "Record_ID",
    "Source_ID",
    "Source_Code",
    "PropertyId",
    "Name",
    "Amenity",
    "Prior",
    "PriorDate",
    "Current",
    "CurrentDate",
    "Proposed",
    "ProposedDate",
    "Notes",
]

# --- ResUnitTypes ----
RES_UNIT_TYPES_SHEET_NAME = "ResUnitTypes"
RES_UNIT_TYPES_COLUMNS: List[str] = [
    "Record_ID",
    "Source_Id",
    "Source_Code",
    "Description",
    "Rent",
    "Deposit",
    "Sqft",
    "PropertyId",
    "Beds",
    "Baths",
    "MinRent",
    "MaxRent",
]

# --- ResUnitTypeDetails ----
RES_UNIT_TYPE_DETAILS_SHEET_NAME = "ResUnitTypeDetails"
RES_UNIT_TYPE_DETAILS_COLUMNS: List[str] = [
    "Record_ID",
    "Source_ID",
    "UnitTypeId",
    "Amount",
    "IsTaxable",
    "IsRecur",
    "MoveIn",
    "Remarks",
    "Acct",
    "ChargeCodeId",
    "IsRequired",
    "IsModified",
    "Instances",
    "Duration",
    "StartMonthsNum",
    "RentObject",
    "IsRoommate",
    "IsSpouse",
    "IsGuarantor",
    "IsOther",
]

# --- CommUnits ----
COMM_UNITS_SHEET_NAME = "CommUnits"
COMM_UNITS_COLUMNS: List[str] = [
    "Record_ID",
    "Source_Id",
    "Source_Code",
    "PropertyId",
    "Exclude",
    "UnitTypeId",
    "Rent",
    "Sqft",
    "IsRentReady",
    "BuildingId",
    "FloorId",
    "HoldUntil",
    "DateReady",
    "RentalType",
    "RentObject",
    "TotalRooms",
    "Status",
    "BedroomCount",
    "AffContractRent",
    "AffSetAside",
    "AffUtilityAllowance",
    "AffContractNo",
    "AffAlternateId",
    "IsPortalExcluded",
    "PortalDisplayRank",
    "DateAvailable",
    "DateVacant",
    "DEPOSIT0",
    "DEPOSIT1",
    "DEPOSIT2",
    "DEPOSIT3",
    "DEPOSIT4",
    "DEPOSIT5",
    "DEPOSIT6",
    "DEPOSIT7",
    "DEPOSIT8",
    "DEPOSIT9",
    "PASTRENT0",
    "PASTRENT1",
    "PASTRENT2",
    "PASTRENT3",
    "PASTRENT4",
    "PASTRENT5",
    "PASTRENT6",
    "PASTRENT7",
    "PASTRENT8",
    "PASTRENT9",
    "PASTRENT10",
    "PASTRENT11",
    "DatePASTRENTINC0",
    "DatePASTRENTINC1",
    "DatePASTRENTINC2",
    "DatePASTRENTINC3",
    "DatePASTRENTINC4",
    "DatePASTRENTINC5",
    "DatePASTRENTINC6",
    "DatePASTRENTINC7",
    "DatePASTRENTINC8",
    "DatePASTRENTINC9",
    "DatePASTRENTINC10",
    "DatePASTRENTINC11",
    "Performance",
]

# --- ResTenants ----
RES_TENANTS_SHEET_NAME = "ResTenants"
RES_TENANTS_COLUMNS: List[str] = [
    "Record_ID",
    "Source_ID",
    "Source_Code",
    "FirstName",
    "LastName",
    "MiddleName",
    "Salutation",
    "Address1",
    "Address2",
    "Address3",
    "Address4",
    "ExtraAddressLine",
    "City",
    "State",
    "ZipCode",
    "GovernmentId",
    "Gets1099",
    "Status",
    "PropertyId",
    "UnitId",
    "Rent",
    "LeaseFrom",
    "LeaseTo",
    "MoveIn",
    "MoveOut",
    "NoticeDate",
    "LastRenewalDate",
    "LeaseSignDate",
    "PaymentType",
    "PayableType",
    "AchOptOut",
    "Email",
    "Email2",
    "LateFeeMinimum",
    "LateFeePerDay",
    "LateFeeType",
    "LateFeeGraceDays",
    "LateFeePercent",
    "LateFeeGraceDays2",
    "LateFeeAmount2",
    "LateFeePercent2",
    "LateFeeMax",
    "LateFeeMaxPercent",
    "LateFeeMaxDays",
    "LateFeeAmountTypeMax",
    "LateFeeAmountType2",
    "LateFeeMinDue",
    "LeaseGrossSqft",
    "HasDepositAccounting",
    "MaintenanceNotes",
    "DueDay",
    "LateMonthDeposit",
    "DepositInterest",
    "LeaseDescription",
    "BedId",
    "IsBillToCustomer",
    "ApplicantId",
    "ReasonForMoveOut",
    "NsfCount",
    "LateFeeCount",
    "ProspectId",
    "IsMTM",
    "LeaseTerm",
    "NoticeType",
    "TotalCharges",
    "AffTenantType",
    "CancelMoveInDate",
    "NoticeResponsibilityDate",
    "DEPOSIT0",
    "DEPOSIT1",
    "DEPOSIT2",
    "DEPOSIT3",
    "DEPOSIT4",
    "DEPOSIT5",
    "DEPOSIT6",
    "DEPOSIT7",
    "DEPOSIT8",
    "DEPOSIT9",
    "PHONENUM0",
    "PHONENUM1",
    "PHONENUM2",
    "PHONENUM3",
    "PHONENUM4",
    "PHONENUM5",
    "PHONENUM6",
    "PHONENUM7",
    "PHONENUM8",
    "PHONENUM9",
    "IsEmployeeUnit",
    "BillToTenant",
    "MaintenanceBillTo",
    "OptForCRMEmails",
    "NonResident",
]

# --- ResProspects ----
RES_PROSPECTS_SHEET_NAME = "ResProspects"
RES_PROSPECTS_COLUMNS: List[str] = [
    "Record_ID",
    "Source_ID",
    "Source_Code",
    "ParentId",
    "TenantId",
    "FirstName",
    "MiddleName",
    "LastName",
    "Salutation",
    "Address1",
    "Address2",
    "Address3",
    "Address4",
    "City",
    "State",
    "ZipCode",
    "HomePhone",
    "OfficePhone",
    "CellPhone",
    "Fax",
    "GovernmentId",
    "Email",
    "AltEmail",
    "PropertyId",
    "UnitTypeId",
    "UnitId",
    "LeaseFrom",
    "LeaseTo",
    "Source",
    "SecondarySource",
    "Agent",
    "FirstContact",
    "FirstShow",
    "ApplyDate",
    "ApproveDate",
    "CancelDate",
    "DenyDate",
    "FirstContactType",
    "IsStudent",
    "LeaseTerm",
    "LeadCrossRefId",
    "DOB",
    "DriversLicense",
    "DriversLicenseState",
    "EmploymentCompany",
    "EmploymentPosition",
    "EmploymentStartDate",
    "EmploymentAddress1",
    "EmploymentAddress2",
    "EmploymentCity",
    "EmploymentState",
    "EmploymentZipCode",
    "EmploymentPhone",
    "Notes",
    "PreferredMoveInDate",
    "PreferredBedrooms",
    "PreferredRent",
    "Is50059",
    "IsTaxCredit",
    "IsHome",
    "IsRd",
    "FailedValidation",
    "AffLeaseStep",
    "Subsidized",
    "HowLong",
    "CardNumber",
    "CardType",
    "CardExpiration",
    "Payment",
    "CheckNumber",
    "Occupant",
    "Relationship",
    "TelAlt",
    "LeaseStep",
    "IType",
    "Income",
    "PreferredBath",
    "QuotedRent",
    "Weblinks",
    "WeblinksStep",
    "License1",
    "License2",
    "State1",
    "State2",
    "EmergencyContactTelHome",
    "Previous2Address1",
    "Previous2Address2",
    "Previous2City",
    "Previous2State",
    "Previous2Zipcode",
    "ShowAgent",
    "PrevAddress1",
    "PrevAddress2",
    "PrevCity",
    "PrevState",
    "PrevZip",
    "PrevHowLong",
    "EmergencyContactName",
    "EmergencyContactRelation",
    "EmergencyContactPhone",
    "AutoMake1",
    "AutoColor1",
    "AutoMake2",
    "AutoColor2",
    "MaidenName",
    "CurrentAddressStartDate",
    "CurrentAddressMonthlyRent",
    "CurrentAddressReasonForMoving",
    "PrevAddressStartDate",
    "PrevAddressMonthlyRent",
    "PrevAddressReasonForMoving",
    "EmplAdditionalIncome",
    "EmplAdditionalIncomeSource",
    "EmergencyContactAddress1",
    "EmergencyContactAddress2",
    "EmergencyContactCity",
    "EmergencyContactState",
    "EmergencyContactZip",
    "OnlineLease",
    "AutoModel1",
    "AutoYear1",
    "AutoModel2",
    "AutoYear2",
    "EmploymentStatus",
    "Status",
    "License3",
    "License4",
    "State3",
    "State4",
    "AutoMake3",
    "AutoColor3",
    "AutoMake4",
    "AutoColor4",
    "AutoModel3",
    "AutoYear3",
    "AutoModel4",
    "AutoYear4",
    "MaritalStatus",
    "CurAddrApartmentCommunity",
    "CurAddrMgmtCompany",
    "CurAddrMgmtCompanyPhone",
    "CurAddr30DayNoticeGiven",
    "PrevAddrApartmentCommunity",
    "PrevAddrMgmtCompany",
    "PrevAddrMgmtCompanyPhone",
    "PrevAddr30DayNoticeGiven",
    "EmpSupervisorName",
    "PrevEmpCompany",
    "PrevEmpPosition",
    "PrevEmpAddr1",
    "PrevEmpAddr2",
    "PrevEmpCity",
    "PrevEmpState",
    "PrevEmpZip",
    "PrevEmpPhone",
    "PrevEmpSupervisorName",
    "PrevEmpStartDate",
    "PrevIncome",
    "PrevEmpAddlIncome",
    "PrevEmpAddlIncomeSource",
    "PrevEmpEndDate",
    "ScreeningIsEvicted",
    "ScreeningIsEvictedDetail",
    "ScreeningIsConvictedFelony",
    "ScreeningIsCriminalChgPending",
    "ScreeningIsCriminalChgPendingDetail",
    "ScreeningIsConvictedFelonyDetail",
    "OccupantType",
    "LeadStage",
    "LeadScore",
    "RoommateId",
]

# --- ResRoommates ----
RES_ROOMMATES_SHEET_NAME = "ResRoommates"
RES_ROOMMATES_COLUMNS: List[str] = [
    "Record_ID",
    "Source_Id",
    "Source_Code",
    "TenantId",
    "LastName",
    "FirstName",
    "MiddleName",
    "Salutation",
    "Email",
    "GovernmentId",
    "MoveIn",
    "MoveOut",
    "IsOccupant",
    "AchOptOut",
    "Relationship",
    "Notes",
    "Address1",
    "Address2",
    "Address3",
    "Address4",
    "City",
    "State",
    "ZipCode",
    "sField1",
    "sField2",
    "sField3",
    "sField4",
    "sField5",
    "sField6",
    "sField7",
    "sField8",
    "sField9",
    "sField10",
    "SPhone1",
    "SPhone2",
    "SPhone3",
    "SPhone4",
    "OccupantType",
    "AltEmail",
]

# ---- ResUnitAmenities ----
RES_UNIT_AMENITIES_SHEET_NAME = "ResUnitAmenities"
RES_UNIT_AMENITIES_COLUMNS: List[str] = [
    "Record_ID",
    "Source_ID",
    "Source_Code",
    "UnitId",
    "Name",
    "Amenity",
    "Prior",
    "PriorDate",
    "Current",
    "CurrentDate",
    "Proposed",
    "ProposedDate",
    "Notes",
]

# --- ResSpecials ----
RES_SPECIALS_SHEET_NAME = "ResSpecials"
RES_SPECIALS_COLUMNS: List[str] = [
    "Record_ID",
    "Source_ID",
    "UnitTypeId",
    "UnitId",
    "Taxable",
    "StartMonth",
    "PropertyId",
    "Notes",
    "Modifiable",
    "MinLeaseTerm",
    "MaxLeaseTerm",
    "Inactive",
    "FrequencyType",
    "FrequencyNumber",
    "ChargeCodeId",
    "Amount",
    "AmountType",
    "Proration",
    "Description",
    "Created",
    "StartDate",
    "isRenewal",
    "isTransfer",
    "isNewMoveIn",
    "isShowOnPortal",
    "PortalDescription",
    "unitStatus",
]

# --- ResRentableItems ----
RES_RENTABLE_ITEMS_SHEET_NAME = "ResRentableItems"
RES_RENTABLE_ITEMS_COLUMNS: List[str] = [
    "Record_ID",
    "Source_ID",
    "Source_Code",
    "PropertyId",
    "RentableItemTypeId",
    "Description",
    "CurrentCamruleId",
    "Rent",
    "ReservedUntil",
    "ProspectReservedId",
    "TenantReservedId",
    "iStatus",
    "TenantId",
]

# --- ResLeaseCharges ----
RES_LEASE_CHARGES_SHEET_NAME = "ResLeaseCharges"
RES_LEASE_CHARGES_COLUMNS: List[str] = [
    "Record_ID",
    "Source_ID",
    "TenantId",
    "ChargeCodeId",
    "Amount",
    "FromDate",
    "ToDate",
    "Notes",
    "EstimateType",
    "MinType",
    "MaxType",
    "TaxRate",
    "TaxcTypeId",
    "Hold",
    "MaxMo",
    "LastPostedDate",
    "ThisMo",
    "IsLateFee",
    "InactiveDate",
    "IsCrCd",
    "IsACH",
]

# -- ResProspectHistories ----
RES_PROSPECT_HISTORIES_SHEET_NAME = "ResProspectHistories"
RES_PROSPECT_HISTORIES_COLUMNS: List[str] = [
    "Record_ID",
    "Source_ID",
    "ProspectId",
    "PropertyId",
    "UnitId",
    "Type",
    "Agent",
    "DateStamp",
    "TimeStamp",
    "Notes",
    "IsFirstContact",
    "IsFirstShow",
    "IsCalendar",
    "Result",
    "IsUnqualified",
    "IsWebLinks",
    "EndDate",
    "Status",
]

# -- ResLeaseHistories ----
RES_LEASE_HISTORIES_SHEET_NAME = "ResLeaseHistories"
RES_LEASE_HISTORIES_COLUMNS: List[str] = [
    "Record_ID",
    "Source_ID",
    "TenantId",
    "LeaseFrom",
    "LeaseTo",
    "DateOccurred",
    "Status",
    "Rent",
    "Term",
    "Term2",
    "Sqft",
    "StatusId",
    "Inactive",
    "DateApproved",
    "DateProposed",
    "DateDenied",
    "Agent",
    "DateScheduled",
    "ProposalDescription",
    "Basis",
    "IncreaseType",
    "NotToExceed",
    "IncreaseAmount",
    "DateSelected",
    "ApprovedMinTerm",
    "DateCancelSelected",
    "PortalSelection",
]

# -- ResTenantHistories ----
RES_TENANT_HISTORIES_SHEET_NAME = "ResTenantHistories"
RES_TENANT_HISTORIES_COLUMNS: List[str] = [
    "Record_ID",
    "Source_ID",
    "EventDate",
    "TenantId",
    "EventType",
    "DateOccurred",
    "UnitId",
    "ApplyDate",
    "ApproveDate",
    "SignDate",
    "MoveIn",
    "MoveOut",
    "LeaseFrom",
    "LeaseTo",
    "NoticeDate",
    "IsRentedEvent",
    "IsUnRentedEvent",
    "TenantStatus",
    "Rent",
    "Deposit",
    "Sqft",
    "Notes",
    "Reason",
    "IsMTM",
    "Agent",
    "ActivityType",
]

#   -- ResUnitHistories ----
RES_UNIT_HISTORIES_SHEET_NAME = "ResUnitHistories"
RES_UNIT_HISTORIES_COLUMNS: List[str] = [
    "Record_ID",
    "Source_ID",
    "UnitId",
    "EventType",
    "Date",
    "Rent",
    "Deposit",
    "Sqft",
    "SetAside",
    "UtilityAllowance",
    "ContractRent",
    "RDBasicRent",
    "Sec236BasicRent",
]

# --- ResUnitStatuses ----
RES_UNIT_STATUSES_SHEET_NAME = "ResUnitStatuses"
RES_UNIT_STATUSES_COLUMNS: List[str] = [
    "Record_ID",
    "Source_ID",
    "StartDate",
    "EndDate",
    "UnitId",
    "DateOccurred",
    "Status",
    "TenantId",
    "ApplyDate",
    "ApproveDate",
    "SignDate",
    "MoveInDate",
    "MoveOutDate",
    "LeaseFrom",
    "LeaseTo",
    "NoticeDate",
    "AvailableDate",
    "IsRentReady",
    "VacantDate",
    "ReadyDate",
]

# --- MaintWorkOrders ----
MAINT_WORK_ORDERS_SHEET_NAME = "MaintWorkOrders"
MAINT_WORK_ORDERS_COLUMNS: List[str] = [
    "Record_ID",
    "Source_ID",
    "Source_Code",
    "BriefDesc",
    "PropertyID",
    "UnitID",
    "TenantID",
    "VendorID",
    "Tax",
    "Payables",
    "Charges",
    "PayableFromCharge",
    "ExternalDescription",
    "Printed",
    "OKToEnter",
    "TenantIsResponsible",
    "CommType",
    "CommAmount",
    "TotalPayableAmount",
    "TotalChargeAmount",
    "CommPercentatge",
    "NotToExceedAmount",
    "Category",
    "SubCategory",
    "AuthorizedBy",
    "Status",
    "Priority",
    "CallerName",
    "PhoneNumber",
    "Email",
    "FullDescription",
    "ProblemDescriptionNotes",
    "AccessNotes",
    "TechnicianNotes",
    "InvoiceDate",
    "BatchName",
    "CallDate",
    "ScheduledDate",
    "InProgressDate",
    "WorkCompletedDate",
    "CanceledDate",
    "InvoiceNumber",
    "OccupantID",
    "InDate",
    "UpdateDate",
    "RequestedBy",
    "UpdatedBy",
    "Use",
    "DateDue",
    "AssignTo",
    "DontCheckout",
    "Followup",
    "PhoneNumber1",
    "Resolution",
    "CallCenter",
    "BuildingId",
    "OriginalsCode",
    "ImportNotes",
    "UserDefinedDates0",
    "UserDefinedDates1",
    "UserDefinedDates2",
    "UserDefinedDates3",
    "UserDefinedDates4",
    "Origin",
    "ExchRate",
]

# --- CommonMemos ----
COMMON_MEMOS_SHEET_NAME = "CommonMemos"
COMMON_MEMOS_COLUMNS: List[str] = [
    "Record_ID",
    "Source_ID",
    "Pointer",
    "TableConstant",
    "Date",
    "Text",
    "EventIndex",
    "EventDescription",
    "PropertyId",
    "UnitId",
    "UnitTypeId",
    "AgentName",
    "Status",
    "Result",
    "EmployeeId",
    "ShowOnCalendar",
    "iField",
    "VendoreCode",
]

# --- GlTenantLedgerHistories ----
GL_TENANT_LEDGER_HISTORIES_SHEET_NAME = "GlTenantLedgerHistories"
GL_TENANT_LEDGER_HISTORIES_COLUMNS: List[str] = [
    "Record_ID",
    "Source_ID",
    "TenantID",
    "TransType",
    "TransDate",
    "PostDate",
    "Notes",
    "Amount",
    "TransID",
    "ChargeCodeID",
    "OffestAccountID",
]

# --- CommAddresses ----
COMM_ADDRESSES_SHEET_NAME = "CommAddresses"
COMM_ADDRESSES_COLUMNS: List[str] = [
    "Record_ID",
    "Source_ID",
    "Source_Code",
    "TableConstant",
    "Pointer",
    "Address1",
    "Address2",
    "Address3",
    "Address4",
    "City",
    "State",
    "ZipCode",
]

# -- ResProposalLeaseCharges ----
RES_PROPOSAL_LEASE_CHARGES_SHEET_NAME = "ResProposalLeaseCharges"
RES_PROPOSAL_LEASE_CHARGES_COLUMNS: List[str] = [
    "Record_ID",
    "Source_Id",
    "LeaseHistoryId",
    "CurrentCamruleId",
    "NewCamruleId",
    "ChargeCodeId",
    "TenantId",
    "FromDate",
    "ToDate",
    "EstimateType",
    "Amount",
    "IncreaseAmount",
    "IncreaseType",
    "Type",
    "Notes",
    "UnitId",
    "PropertyId",
    "DateToCamRule",
    "DoNotRenew",
    "SpecialId",
    "SpecialPercent",
]

# -- ResResPersonPets ----
RES_RES_PERSON_PETS_SHEET_NAME = "ResResPersonPets"
RES_RES_PERSON_PETS_COLUMNS: List[str] = [
    "Record_ID",
    "Source_ID",
    "ProspectId",
    "PersonId",
    "PetType",
    "PetWeight",
    "PetAge",
    "PetColor",
    "PetName",
    "PetBreed",
    "PetGender",
    "PetSpayed",
]

# --- ResProspectCharges ----
RES_PROSPECT_CHARGES_SHEET_NAME = "ResProspectCharges"
RES_PROSPECT_CHARGES_COLUMNS: List[str] = [
    "Record_ID",
    "Source_ID",
    "ProspectId",
    "TenantId",
    "RentScheduleId",
    "UnitDetID",
    "sType",
    "Amount",
    "Deposit",
    "OneTime",
    "Concession",
    "Quantity",
    "StartMonth",
    "Duration",
    "LeaseTerm",
    "Frequency",
    "ChargeCodeId",
    "Description",
    "Taxable",
    "RentableItemId",
]

# --- ResMoveInCharges ----
RES_MOVE_IN_CHARGES_SHEET_NAME = "ResMoveInCharges"
RES_MOVE_IN_CHARGES_COLUMNS: List[str] = [
    "Record_ID",
    "Source_ID",
    "TenantId",
    "ProspectId",
    "RecordId",
    "RecordType",
    "LeaseAmount",
    "MoveInAmount",
    "AccountId",
    "ARAccountId",
    "MonthsToStart",
    "Duration",
    "ChargeDescription",
    "ChargeCodeId",
    "RentableItemId",
    "IsTax",
    "IsRecurring",
    "IsModify",
    "IsRequired",
    "IsProrate",
    "IsSelected",
    "IsDisableLeaseAmount",
    "IsDisableMoveInAmount",
    "ChargeDate",
    "PostMonth",
    "PostedDate",
    "PostedUserId",
    "LastModifiedDate",
    "LastModifiedUserId",
    "IsRentableItem",
    "IsSpecial",
    "AmountPercent",
]

# --- FinCharges ----
FIN_CHARGES_SHEET_NAME = "FinCharges"
FIN_CHARGES_COLUMNS: List[str] = [
    "Record_ID",
    "Source_ID",
    "iType",
    "PropertyId",
    "myOpen",
    "PersonId",
    "myChargeReference",
    "Date",
    "PostMonth",
    "Amount",
    "AccountId",
    "ArAccountId",
    "TaxType",
    "ChargeCodeId",
    "Reference",
    "UserDefined1",
    "myFullyPaidById",
    "myFullyPaidDate",
    "BatchId",
    "myAmountPaid",
    "IsOnHold",
    "IsConsolidated",
    "UserDefinedFields1",
    "UserDefinedFields2",
    "UserDefinedFields3",
    "UserDefinedFields4",
    "UserDefinedFields5",
    "UserDefinedFields6",
    "UserDefinedFields7",
    "UserDefinedFields8",
    "Notes",
    "UnitId",
    "IsAch",
    "JobId",
    "CategoryId",
    "IsCreditCard",
    "CompanyId",
    "FundingEntityId",
    "myVoid",
    "FromDate",
    "ToDate",
    "InvoiceDate",
    "VatRateId",
    "TaxAmount1",
    "TaxAmount2",
    "VatTranTypeId",
    "VatParentId",
    "CreditParentId",
    "OriginalCreditAmount",
    "TaxPointDate",
    "MethodOfPayment",
    "ExchangeRateTypeId",
    "TaxRecordSeqNo",
    "DisplayType",
    "myUserCreatedById",
    "myUserLastModifiedById",
    "myDateCreated",
    "myDateLastModified",
    "myModuleCreatedBy",
    "myModuleModifiedBy",
    "myTranModuleType",
    "myDateTimeStamp",
    "Segment1",
    "Segment2",
    "Segment3",
    "Segment4",
    "Segment5",
    "Segment6",
    "Segment7",
    "Segment8",
    "Segment9",
    "Segment10",
    "Segment11",
    "Segment12",
    "ForBenefitOf",
]

# --- FinPrePayments ----
FIN_PRE_PAYMENTS_SHEET_NAME = "FinPrePayments"
FIN_PRE_PAYMENTS_COLUMNS: List[str] = [
    "Record_ID",
    "Source_ID",
    "PersonId",
    "myPropertyId",
    "Notes",
    "CheckNumber",
    "Date",
    "CashAccountId",
    "UnitId",
    "Cash",
    "CashInt",
    "PostMonth",
    "CompanyId",
    "Reference",
    "AccountId",
    "Amount",
    "DNotes",
    "Segment1",
    "Segment2",
    "Segment3",
    "Segment4",
    "Segment5",
    "Segment6",
    "Segment7",
    "Segment8",
    "Segment9",
    "Segment10",
    "Segment11",
    "Segment12",
    "JobId",
    "CategoryId",
    "ContractId",
    "CostCode",
    "PrepayChargeCode",
    "HoldForChargeCodeId",
    "AutoApply",
    "FundingEntityId",
    "DisplayType",
    "CompanyDueTo",
]

# --- FinDeposits ----
FIN_DEPOSITS_SHEET_NAME = "FinDeposits"
FIN_DEPOSITS_COLUMNS: List[str] = [
    "Record_ID",
    "Source_ID",
    "myType",
    "PersonId",
    "ChargeCodeId",
    "IsNotReconciled",
    "myDepositNumber",
    "Amount",
    "DepositDate",
    "PostMonth",
    "Notes",
    "ChgAcct",
    "ChgPaidAmount",
    "CompanyId",
    "myCash",
    "FundingEntityId",
    "DisplayType",
]

# --- CommonBankXRefs ----
COMMON_BANK_X_REFS_SHEET_NAME = "CommonBankXRefs"
COMMON_BANK_X_REFS_COLUMNS: List[str] = [
    "Record_ID",
    "Source_ID",
    "AccountId",
    "PropertyId",
    "BankId",
    "ARTransitAccount",
    "APTransitAccount",
    "TenantId",
]

# --- ResTenantOtherinfos ----
RES_TENANT_OTHERINFOS_SHEET_NAME = "ResTenantOtherinfos"
RES_TENANT_OTHERINFOS_COLUMNS: List[str] = [
    "Record_ID",
    "Source_Id",
    "TenantId",
    "DriversLicense",
    "DriversLicenseState",
    "EmergencyName",
    "EmergencyRelation",
    "EmergencyPhoneHome",
    "EmergencyPhoneOther",
    "AutoType1",
    "AutoType2",
    "AutoType3",
    "AutoType4",
    "AutoModel1",
    "AutoModel2",
    "AutoModel3",
    "AutoModel4",
    "AutoYear1",
    "AutoYear2",
    "AutoYear3",
    "AutoYear4",
    "AutoColor1",
    "AutoColor2",
    "AutoColor3",
    "AutoColor4",
    "AutoLicense1",
    "AutoLicense2",
    "AutoLicense3",
    "AutoLicense4",
    "AutoState1",
    "AutoState2",
    "AutoState3",
    "AutoState4",
    "EmergencyAddress1",
    "EmergencyAddress2",
    "EmergencyCity",
    "EmergencyState",
    "EmergencyZip",
    "StatementType",
]

# --- FinPayables ----
FIN_PAYABLES_SHEET_NAME = "FinPayables"
FIN_PAYABLES_COLUMNS: List[str] = [
    "Record_ID",
    "Header_ID",
    "Detail_ID",
    "Source_ID",
    "BatchId",
    "PersonId",
    "InvoiceNumber",
    "CashAccountId",
    "ApAccountId",
    "PostMonth",
    "VatReturnMonth",
    "InvoiceDate",
    "DueDate",
    "DiscountDate",
    "DiscountPercent",
    "DiscountAmount",
    "UserDefinedFields0",
    "UserDefinedFields1",
    "UserDefinedFields2",
    "UserDefinedFields3",
    "UserDefinedFields4",
    "UserDefinedFields5",
    "UserDefinedFields6",
    "UserDefinedFields7",
    "UserDefinedFields8",
    "UserDefinedFields9",
    "ExpenseType",
    "GetCheckMemoFromInvoice",
    "ReverserId",
    "Type",
    "Type1",
    "PropertyIdGetType",
    "IsUnpaid",
    "Amount",
    "AmountPaid",
    "ManualCheckPostMonth",
    "ManualCheckNumber",
    "ManualCheckDate",
    "RelatedPersonIdGetType",
    "Notes",
    "Void",
    "ConsoloidatePayments",
    "IsCreditMemo",
    "IsAdjustment",
    "Voided",
    "Voider",
    "HoldPayments",
    "ImplicitPostMonthDate",
    "MultiOffset",
    "IsRetention",
    "IsRetPay",
    "ExemptFrom1099",
    "IsAch",
    "ContractId",
    "DisplayType",
    "CompanyIdTrue",
    "FundingEntityIdTrue",
    "PaymentMethod",
    "PayableIdGetType",
    "CheckIdGetType",
    "CheckPostMonth",
    "PayablePostMonth",
    "DateTimeStamp",
    "BankId",
    "PODetailId",
    "TempTaxAmount1",
    "TempTaxAmount2",
    "Amount_Detail",
    "ExpAccount",
    "Notes_Detail",
    "Segment1",
    "Segment2",
    "Segment3",
    "Segment4",
    "Segment5",
    "Segment6",
    "Segment7",
    "Segment8",
    "Segment9",
    "Segment10",
    "Segment11",
    "Segment12",
    "CompanyDueTo",
]

# --- FinVendors ----
FIN_VENDORS_SHEET_NAME = "FinVendors"
FIN_VENDORS_COLUMNS: List[str] = [
    "Record_ID",
    "Source_ID",
    "Source_Code",
    "LastName",
    "WorkersCompExpiration",
    "LiabilityExpiration",
    "DiscountDay",
    "DiscountIsDaysAfterInvoice",
    "DiscountPercent",
    "SalesTaxPercent",
    "UsualCategoryId",
    "IsSubcontractorDB",
    "RequireContract",
    "RetentionPercentage",
    "HoldPayments",
    "Contract",
    "Contact",
    "ConsolidatePayments",
    "NoSignatureDB",
    "UsualAccountId",
    "NoSignatureAmount",
    "IsInactiveDB",
    "InactiveAsOf",
    "CheckMemoFromInvoiceDB",
    "IsPORequired",
    "IsEmployeeDB",
    "Priority",
    "ExpenseType",
    "Status",
    "FirstName",
    "Salutation",
    "Address1",
    "Address2",
    "Address3",
    "Address4",
    "City",
    "State",
    "ZipCode",
    "CountryId",
    "ExtraAddressLine",
    "PhoneNumber0",
    "PhoneNumber1",
    "PhoneNumber2",
    "PhoneNumber3",
    "PhoneNumber4",
    "PhoneNumber5",
    "PhoneNumber6",
    "PhoneNumber7",
    "PhoneNumber8",
    "PhoneNumber9",
    "GovernmentId",
    "GovernmentName",
    "Gets1099",
    "GetsT5018",
    "CheckMemo",
    "Email",
    "Email2",
    "URL",
    "MaintenanceNotes",
    "PrefLanguage",
    "ACH",
    "PayablePaymentMethod",
    "NoDupeInvoiceSameDate",
    "StopPurchaseOrder",
    "DefaultAPAcct",
    "DefaultCashAcct",
    "PaymentTerms",
    "DueDateIsEndOfNextMonth",
    "IsPreferredSupplier",
    "FullServiceDisplayType",
]

# ---CommonPropOwners ----
COMMON_PROP_OWNERS_SHEET_NAME = "CommonPropOwners"
COMMON_PROP_OWNERS_COLUMNS: List[str] = [
    "Record_ID",
    "Source_Id",
    "PropertyId",
    "OwnerId",
    "Percentage",
    "Investment",
    "InvestmentDate",
    "Remarks",
    "Shares",
    "Income",
    "Depreciation",
    "TaxCredit",
    "StateCredit",
    "Type",
]

# -- CreditCheckMITSDetails ----
CREDIT_CHECK_MITS_HEADERS_SHEET_NAME = "CreditCheckMITSHeaders"
CREDIT_CHECK_MITS_HEADERS_COLUMNS: List[str] = [
    "Record_ID",
    "Source_ID",
    "TenantApplicantId",
    "Code",
    "PropertyId",
    "CreditChecker",
    "LeaseMonths",
    "MonthlyRent",
    "SecurityDeposit",
    "TransactionNumber",
    "ReportDate",
    "ApplicantDecision",
    "ApplicantScore",
    "sApplicationDecision",
    "sService",
    "sStatus",
    "bPreview",
]

# -- CreditCheckMITSDetails ----
CREDIT_CHECK_MITS_DETAILS_SHEET_NAME = "CreditCheckMITSDetails"
CREDIT_CHECK_MITS_DETAILS_COLUMNS: List[str] = [
    "Record_ID",
    "Source_ID",
    "TenantApplicantId",
    "Code",
    "MitsId",
    "PersonId",
    "PropertyId",
    "Active",
    "Title",
    "FirstName",
    "LastName",
    "Spouse",
    "MaidenName",
    "MiddleName",
    "NameSuffix",
    "Birthdate",
    "SocSecNumber",
    "ApplicantType",
    "ApplicantIdentifier",
    "CurrentRent",
    "ConsentObtained",
    "EmploymentStatus",
    "EmploymentType",
    "EmployerName",
    "EmploymentGrossIncome",
    "EmploymentStartDate",
    "EmploymentStartDate2",
    "EmploymentEndDate",
    "EmploymentEndDate2",
    "OtherIncomeAmount",
    "OtherIncomeType",
    "OtherIncomePeriod",
    "Assets",
    "TotalLiabilities",
    "NetWorth",
    "EmploymentVerification",
    "AddressType1",
    "AddressType2",
    "AddressType3",
    "UnparsedAddress1",
    "UnparsedAddress2",
    "UnparsedAddress3",
    "StreetNumber1",
    "StreetNumber2",
    "StreetNumber3",
    "StreetName1",
    "StreetName2",
    "StreetName3",
    "StreetType1",
    "StreetType2",
    "StreetType3",
    "ApartmentNumber1",
    "ApartmentNumber2",
    "ApartmentNumber3",
    "City1",
    "City2",
    "City3",
    "State1",
    "State2",
    "State3",
    "Zipcode1",
    "Zipcode2",
    "Zipcode3",
    "Country1",
    "Country2",
    "Country3",
    "DateMoveIn1",
    "DateMoveIn2",
    "DateMoveIn3",
    "DateMoveOut1",
    "DateMoveOut2",
    "DateMoveOut3",
    "AddressVerification1",
    "AddressVerification2",
    "AddressVerification3",
    "ROHistory1",
    "ROHistory2",
    "ROHistory3",
    "DriversLicense",
    "DriversLicenseState",
    "Guarantor",
    "Email",
    "ProspectId",
    "SummaryId",
    "IsSSNNotAvailable",
    "ReevaluateTypes",
    "ReevaluateNotes",
    "CriminalRecordType",
    "CriminalRecordDescriptions",
    "DateCriminalRecord",
    "HasCriminalRecord",
    "Origin",
    "Updated",
    "TypeOtherId",
    "OtherId",
    "CtryOfIssue",
    "PersonType",
]

# ---CreditCheckMitSMultiRepss ----
CREDIT_CHECK_MITS_MULTI_REPSS_SHEET_NAME = "CreditCheckMitsMultiRepss"
CREDIT_CHECK_MITS_MULTI_REPSS_COLUMNS: List[str] = [
    "Record_ID",
    "Source_ID",
    "MitsId",
    "CreditChecker",
    "Report",
    "TransactionNumber",
    "ApplicantDecision",
    "ApplicationDecision",
    "ApplicantScore",
    "ReportDate",
    "Equifax",
    "Experian",
    "TransUnion",
    "NativeAgency",
    "CrossCheck",
    "Status",
    "ReportSelect",
    "ActiveSelection",
    "Custom1",
    "Custom2",
    "Custom3",
    "Custom4",
    "Custom5",
    "Custom6",
    "Custom7",
    "Custom8",
    "CreditAppDecision",
]

# -- CreditCheckMITSRepXrefs ----
CREDIT_CHECK_MITS_REP_XREFS_SHEET_NAME = "CreditCheckMITSRepXrefs"
CREDIT_CHECK_MITS_REP_XREFS_COLUMNS: List[str] = [
    "Record_ID",
    "Source_ID",
    "hMitsRep",
    "hMitsDetail",
]

# -- ResInterfaceLogins ----
RES_INTERFACE_LOGINS_SHEET_NAME = "ResInterfaceLogins"
RES_INTERFACE_LOGINS_COLUMNS: List[str] = [
    "Record_ID",
    "Source_Id",
    "PropertyId",
    "InterfaceId",
    "InterfaceName",
    "OriginatorId",
    "AccountId",
    "PropOptionsPropId",
    "PropOptionsPropId2",
    "IsTestProp",
    "iType",
    "Option1",
    "Option2",
    "sOption1",
    "sOption2",
    "sOption3",
    "SetApplicantInactive",
    "SetApplicantInactiveOnCond",
    "UpdateWithBaseRent",
    "UpdateUnitTypeRent",
    "UpdateUnitRent",
    "LeaseTermForPricing",
    "UseRMConcessions",
]

# --- ResInterfacePortalAdmins ----
RES_INTERFACE_PORTAL_ADMINS_SHEET_NAME = "ResInterfacePortalAdmins"
RES_INTERFACE_PORTAL_ADMINS_COLUMNS: List[str] = [
    "Record_ID",
    "Source_Id",
    "InterfaceLoginId",
    "PropertyId",
    "Report",
    "SendToEquifax",
    "SendToExperian",
    "SendToTransunion",
    "SendToNative",
    "PortalUserName",
    "PortalOriginatorId",
    "PortalAccountId",
    "Custom1",
    "Custom2",
    "Custom3",
    "Custom4",
    "PortalPropertyIdMap",
]

# --- ResCreditCheckRepXrefs ----
RES_CREDIT_CHECK_REP_XREFS_SHEET_NAME = "ResCreditCheckRepXrefs"
RES_CREDIT_CHECK_REP_XREFS_COLUMNS: List[str] = [
    "Record_ID",
    "PropertyId",
    "ListName",
    "Source_Code",
]

# --- CommonAttachments ----
COMMON_ATTACHMENTS_SHEET_NAME = "CommonAttachments"
COMMON_ATTACHMENTS_COLUMNS: List[str] = [
    "Record_ID",
    "Source_ID",
    "Type",
    "Record",
    "File",
    "Description",
    "IsSecure",
    "ScannedImagePDF",
    "IsWebLinks",
    "ImagesId",
    "IsAttached",
    "AttachmentType",
]



# One place to register all tables you want to export
TABLE_SPECS: Dict[str, TableSpec] = {
    "comm_properties": {
        "sheet_name": COMM_PROPERTIES_SHEET_NAME,
        "row_tag": "CommProperty",
        "columns": COMM_PROPERTIES_COLUMNS,
        "root_path": ["DataSection", "CommProperties"],
    },
    "lock_outs": {
        "sheet_name": LOCK_OUTS_SHEET_NAME,
        "row_tag": "LockOut",
        "columns": LOCK_OUTS_COLUMNS,
        "root_path": ["DataSection", "LockOuts"],
    },
    "res_source_names": {
        "sheet_name": RES_SOURCE_NAMES_SHEET_NAME,
        "row_tag": "ResSourceName",
        "columns": RES_SOURCE_NAMES_COLUMNS,
        "root_path": ["DataSection", "ResSourceNames"],
    },
    "res_agent_names": {
        "sheet_name": RES_AGENT_NAMES_SHEET_NAME,
        "row_tag": "ResAgentName",
        "columns": RES_AGENT_NAMES_COLUMNS,
        "root_path": ["DataSection", "ResAgentNames"],
    },
    "res_cancel_reasons": {
        "sheet_name": RES_CANCEL_REASONS_SHEET_NAME,
        "row_tag": "ResCancelReason",
        "columns": RES_CANCEL_REASONS_COLUMNS,
        "root_path": ["DataSection", "ResCancelReasons"],
    },
    "res_rentables_items_types": {
        "sheet_name": RES_RENTABLE_ITEMS_TYPES_SHEET_NAME,
        "row_tag": "ResRentableItemsType",
        "columns": RES_RENTABLE_ITEMS_TYPES_COLUMNS,
        "root_path": ["DataSection", "ResRentableItemsTypes"],
    },
    "common_prop_options": {
        "sheet_name": COMMON_PROP_OPTIONS_SHEET_NAME,
        "row_tag": "CommonPropOption",
        "columns": COMMON_PROP_OPTIONS_COLUMNS,
        "root_path": ["DataSection", "CommonPropOptions"],
    },
    
    
}
