import xml.etree.ElementTree as ET
from typing import List
from openpyxl.worksheet.worksheet import Worksheet
from .utils import strip_namespace, safe_text

SHEET_NAME = "ResProspects"

RES_PROSPECTS_COLUMNS: List[str] = [
    "Record_ID",
    "Source_ID",
    "Source_Code",
    "ParentId",
    "TenantId",
    "FirstName",
    "MiddleName",
    "LastName",
    "Salutation",
    "Address1",
    "Address2",
    "Address3",
    "Address4",
    "City",
    "State",
    "ZipCode",
    "HomePhone",
    "OfficePhone",
    "CellPhone",
    "Fax",
    "GovernmentId",
    "Email",
    "AltEmail",
    "PropertyId",
    "UnitTypeId",
    "UnitId",
    "LeaseFrom",
    "LeaseTo",
    "Source",
    "SecondarySource",
    "Agent",
    "FirstContact",
    "FirstShow",
    "ApplyDate",
    "ApproveDate",
    "CancelDate",
    "DenyDate",
    "FirstContactType",
    "IsStudent",
    "LeaseTerm",
    "LeadCrossRefId",
    "DOB",
    "DriversLicense",
    "DriversLicenseState",
    "EmploymentCompany",
    "EmploymentPosition",
    "EmploymentStartDate",
    "EmploymentAddress1",
    "EmploymentAddress2",
    "EmploymentCity",
    "EmploymentState",
    "EmploymentZipCode",
    "EmploymentPhone",
    "Notes",
    "PreferredMoveInDate",
    "PreferredBedrooms",
    "PreferredRent",
    "Is50059",
    "IsTaxCredit",
    "IsHome",
    "IsRd",
    "FailedValidation",
    "AffLeaseStep",
    "Subsidized",
    "HowLong",
    "CardNumber",
    "CardType",
    "CardExpiration",
    "Payment",
    "CheckNumber",
    "Occupant",
    "Relationship",
    "TelAlt",
    "LeaseStep",
    "IType",
    "Income",
    "PreferredBath",
    "QuotedRent",
    "Weblinks",
    "WeblinksStep",
    "License1",
    "License2",
    "State1",
    "State2",
    "EmergencyContactTelHome",
    "Previous2Address1",
    "Previous2Address2",
    "Previous2City",
    "Previous2State",
    "Previous2Zipcode",
    "ShowAgent",
    "PrevAddress1",
    "PrevAddress2",
    "PrevCity",
    "PrevState",
    "PrevZip",
    "PrevHowLong",
    "EmergencyContactName",
    "EmergencyContactRelation",
    "EmergencyContactPhone",
    "AutoMake1",
    "AutoColor1",
    "AutoMake2",
    "AutoColor2",
    "MaidenName",
    "CurrentAddressStartDate",
    "CurrentAddressMonthlyRent",
    "CurrentAddressReasonForMoving",
    "PrevAddressStartDate",
    "PrevAddressMonthlyRent",
    "PrevAddressReasonForMoving",
    "EmplAdditionalIncome",
    "EmplAdditionalIncomeSource",
    "EmergencyContactAddress1",
    "EmergencyContactAddress2",
    "EmergencyContactCity",
    "EmergencyContactState",
    "EmergencyContactZip",
    "OnlineLease",
    "AutoModel1",
    "AutoYear1",
    "AutoModel2",
    "AutoYear2",
    "EmploymentStatus",
    "Status",
    "License3",
    "License4",
    "State3",
    "State4",
    "AutoMake3",
    "AutoColor3",
    "AutoMake4",
    "AutoColor4",
    "AutoModel3",
    "AutoYear3",
    "AutoModel4",
    "AutoYear4",
    "MaritalStatus",
    "CurAddrApartmentCommunity",
    "CurAddrMgmtCompany",
    "CurAddrMgmtCompanyPhone",
    "CurAddr30DayNoticeGiven",
    "PrevAddrApartmentCommunity",
    "PrevAddrMgmtCompany",
    "PrevAddrMgmtCompanyPhone",
    "PrevAddr30DayNoticeGiven",
    "EmpSupervisorName",
    "PrevEmpCompany",
    "PrevEmpPosition",
    "PrevEmpAddr1",
    "PrevEmpAddr2",
    "PrevEmpCity",
    "PrevEmpState",
    "PrevEmpZip",
    "PrevEmpPhone",
    "PrevEmpSupervisorName",
    "PrevEmpStartDate",
    "PrevIncome",
    "PrevEmpAddlIncome",
    "PrevEmpAddlIncomeSource",
    "PrevEmpEndDate",
    "ScreeningIsEvicted",
    "ScreeningIsEvictedDetail",
    "ScreeningIsConvictedFelony",
    "ScreeningIsCriminalChgPending",
    "ScreeningIsCriminalChgPendingDetail",
    "ScreeningIsConvictedFelonyDetail",
    "OccupantType",
    "LeadStage",
    "LeadScore",
    "RoommateId",
]


def export_resprospects(xml_path: str, ws: Worksheet) -> None:
    """
    Writes one sheet:
      DataSection/ResProspects/ResProspect -> rows
    """
    ws.title = SHEET_NAME
    ws.append(RES_PROSPECTS_COLUMNS)

    # Stream parse; write a row when </ResProspect> closes
    for event, elem in ET.iterparse(xml_path, events=("end",)):
        if strip_namespace(elem.tag) == "ResProspect":
            row_map = {c: "" for c in RES_PROSPECTS_COLUMNS}

            for child in elem:
                key = strip_namespace(child.tag)
                if key in row_map:
                    row_map[key] = safe_text(child.text)

            ws.append([row_map[c] for c in RES_PROSPECTS_COLUMNS])
            elem.clear()
